codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: 70..100

  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "contracts/test/**"
  - "contracts/lens/**"
  - "contracts/oz/**"
  - "contracts/Proxies.sol"
  - "src/**"
  - "tasks/**"
