name: Test

on:
  push:

env:
  RPC_ETH: ${{ secrets.RPC_ETH }}
  ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}

jobs:
  compile-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - run: npx hardhat --version
      - run: npm ci
      - run: npm run compile
      - run: npm run test
